config/routes.rb
ShiningSeaMultisite::Application.routes.draw do
  devise_for :users
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  # Default to the documentation and examples
  root :to => 'documentation#index'

  # Quick tools section
  match "tools" => "tools#index", :via => :get, :as => :tools
  match "tools/twitter" => "tools#twitter_list", :via => :post, :as => :twitter_list
  
  get "site/:id" => "sites#show"
  get "site/:id/:screen_name/status/:tweet_id" => "tweets#show"

  get "iframes/:id" => "sites#iframe"

  get "site/:id/not_found" => "sites#not_found"
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  layout false
  
  def show
    @site = Site.find(params[:id])
    @account = @site.accounts.find_by_screen_name(params[:screen_name])
    @tweet = @account.tweet_metrics.find_by_tweet_id(params[:tweet_id])
    
    @date = @tweet.published_at.in_time_zone(@site.time_zone)
    
    @daily_prev = @tweet.previous_by_rank
    @daily_next = @tweet.next_by_rank
  end
end
  

app/views/tweets/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script type="text/javascript" src="http://use.typekit.com/bvc1jkf.js"></script>
  	<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
    <title><%= @site.name %> - #<%= @tweet.daily_rank %> on <%= pretty_date(@date) %> 
      from @<%= @account.screen_name %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/assets/css/ggt.css" rel="stylesheet" media="screen">
    <link rel="stylesheet" href="/assets/font-awesome/css/font-awesome.min.css">
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <link href='http://fonts.googleapis.com/css?family=Roboto:300' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
  <script type="text/javascript">
      $(document).ready(function(){
        $('#content-registration .registration').css('display','none');
        function toggle_login_form(){
          $('#myModal').removeClass('modal');
          $('#modal-backdrop').removeClass('modal-dropbox');
          $('#modal-backdrop').css('height','30px');
          $('.send_to_mv').click(function(){
            if (document.cookie.indexOf("account_data") > -1){
              var get_send_to_mv_id = this.parentElement.getAttribute('id');
              var get_number = get_send_to_mv_id.split("send_to_mv")[1];
              var to_channel_id = "to_channel" + get_number;
              $("#"+to_channel_id).show();
              $(this).hide();
            }
            else{
              $('#myModal').addClass('modal');
              $('#modal-backdrop').addClass('modal-dropbox');
              $('#myModal').modal('toggle');
              $('.hover-content').css('z-index',1);
            }
          });
        }
        toggle_login_form();
        function logged_in(){
          if (document.cookie.indexOf("account_data") > -1){
            function getCookie(cname) {
              var name = cname + "=";
              var ca = document.cookie.split(';');
              for(var i=0; i<ca.length; i++) {
                var c = ca[i];
                while (c.charAt(0)==' ') c = c.substring(1);
                if (c.indexOf(name) == 0) return c.substring(name.length,c.length);
              }
              return "";
            }
            $('.logout-form').click(function(){
              document.cookie.split(";").forEach(function(c) { document.cookie = c.replace(/^ +/, "").replace(/=.*/, "=;expires=" + new Date().toUTCString() + ";path=/"); });
              $('#before_login').show();
              $('#after_login').hide();
              var x = document.getElementsByClassName("hover-content");
              var i;
              for (i = 0; i < x.length; i++) {
                var hover_content = "";
                x[i].innerHTML = hover_content;
              }
            })
            var account_cookie = unescape(getCookie("account_data"));
            var account_data_cookie = account_cookie.replace(/\+/gi, " ").split(",");
            var x = document.getElementsByClassName("hover-content");
            var i;
            $('#before_login').hide();
            $('#after_login').show();
            for (i = 0; i < x.length; i++) {
              var hover_content = "<div class='send_to_mv' id='send_to_mv_"+i.toString()+"'><button class='channel_name btn-primary btn send_to_mv'>Send To MV</button></div><div class='to_channel' id='to_channel_"+i.toString()+"'> <div class='channel_name btn-primary btn'>To Channel</div><div class='parent-buttons'>";
              for (var j = account_data_cookie.length - 1; j > 0; j--) {
                hover_content += "<a href='#' class='each_channel_name'>#"+account_data_cookie[j]+"</a><br>";
              };
              hover_content +="</div></div><div class='sent btn-primary btn'>Sent!</div>"
              x[i].innerHTML = hover_content;
              $('.to_channel').hide();
              $('.sent').hide();
              toggle_login_form();
            }
            $('.each_channel_name').click(function(e) {
              e.preventDefault();
              var tweet_id = this.parentNode.parentNode.parentNode.id;
              var person_id = account_data_cookie[0];
              var channel_name = this.innerHTML;
              var that = this
              var url = "/";
              $.ajax({
                type: "POST",
                url: "https://omnia.measuredvoice.com/api_idea"+".json",
                data: {"tweet_id": tweet_id, "person_id": person_id, "channel_name": channel_name },
                dataType: "html",
                success: function(data) {
                  $("#"+that.parentNode.parentNode.id).hide();
                  $($(that.parentNode.parentNode.parentNode).find($(".sent"))[0]).show()
                  $('.sent').click(function(){
                    $('.send_to_mv').show();
                    $($(that.parentNode.parentNode.parentNode).find($(".sent"))[0]).hide()
                  })
                },
                error: function(err) {
                }
              });
            });
          };
        };
        logged_in();
        $("#new_person").submit(function(e){
          e.preventDefault();
          var email = $("#person_email").val();
          var password = $("#person_password").val();
          var rememberMe = $("#person_remember_me").val();
          var url = "/";
          $.ajax({
            type: "POST",
            url: "https://<%= ENV['MV_HOST'] %>.measuredvoice.com/api_login"+".json",
            data: {"email": email, "password" : password, "remember_me": rememberMe },
            dataType: "html",
            success: function(data) {
              var account_data = JSON.parse(data)
              var d = new Date();
              d.setTime(d.getTime() + (24*60*60*1000));
              var expires = "expires="+d.toUTCString();
              document.cookie='account_data='+account_data + ";domain=.measuredvoice.com;path=/;" + expires;
              $('#before_login').hide();
              $('#after_login').show();
              $('#content-registration').hide();
              logged_in();
              $('.fade').removeClass('in').addClass('out');
              $('.out').removeClass('modal-backdrop');
              $('body').removeClass('modal-open');
            },
            error: function(err) {
              var x = document.getElementsByClassName("error-message");
              x[0].innerHTML = "Invalid Email address or password!";
            }
        });
        })
      })
  </script>
    <%= render "shared/social_sharing_setup" %>
    <div class="container">
      <div class="row">
        <div class="col-lg-2 col-12">
          <div class="twitter-follow-container">
            <%= render :partial => "shared/twitter_follow_button", :locals => { :site => @site } %>
          </div>
        </div>
        <div class="col-lg-10 col-12">
          <span id="mv-logo"><a href="http://measuredvoice.com">Measured Voice, the only social media management tool designed for government.</a></span>  
        </div>
      </div>
      <% if @site.partner_logo_url.present? %>
      <div class="row">
        <div class="col-lg-12 col-12">
          <span id="partner-logo">
            <% if @site.partner_link_url.present? %>
            <a href="<%= @site.partner_link_url %>"><img src="<%= @site.partner_logo_url %>"></a>
            <% else %>
              <img src="<%= @site.partner_logo_url %>">
            <% end %>
          </span>
        </div>
      </div>
      <% end %>
    </div>
    <div class="jumbotron">
      <div class="container">
        <div class="row">
          <div class="brand col-lg-8 col-12">
            <h1><a href="/"><%= @site.name %></a></h1>
            <h3 class="tagline"><%=raw @site.tagline %></h3>
          </div>
        </div>
      </div>
    </div>
  	<div class="container">
  		<div class="row">
        <div class="col-lg-6 col-12">
          <div class="rank-score">
            <div class="col-lg-3 col-3 rank-number">
              <span class="superscript">#</span><%= @tweet.daily_rank %>
            </div>
            <div class="col-lg-9 col-9 rank-details">
              <p>This was the <%= @tweet.daily_rank > 1 ? @tweet.daily_rank.ordinalize : '' %> most engaging Tweet from <%= @site.account_type %> <span class="tweet-date">on <%= pretty_date(@date) %></span>.</p>
            </div>
          </div>
        </div>
       
        <div class="col-lg-6 col-12 pull-right the-tweet">
          <blockquote class="twitter-tweet">
          <p><%= @tweet.tweet_text %></p>
          &mdash; <%= @tweet.account.name %> (@<%= @tweet.account.screen_name %>) 
          <a href="https://twitter.com/<%= @tweet.account.screen_name %>/statuses/<%= @tweet.tweet_id %>"><%= pretty_date(@date) %></a>
          </blockquote>
          <% if @site.cta_iframe.present? %>
          <iframe src="/iframes/<%= @site.id %>" class="mv-ad" id="iframe1"></iframe>
          <% end %>
        </div>  
        <div class="col-lg-6 col-12">
          <div class="tweet-stats-send-mv clearfix">
            <div class="tweet-stats pull-left">
              <p>
                Within its first day, this tweet received<br>
                </i><span class="retweet-count"><i class="icon-retweet"></i> <span class="big-number"><%= pretty_number(@tweet.engagement) %> <%= pluralize(@tweet.engagement, 'retweet', 'retweets') %></span></span><br>
                <span class="favorite-count"><i class="icon-star"></i> <span class="big-number"><%= pretty_number(@tweet.kudos) %>  <%= pluralize(@tweet.kudos, 'favorite', 'favorites') %></span></span><br>
                and reached a potential<br>
                <span class="reach-total"><i class="icon-bullhorn"></i><span class="big-number"><%= pretty_number(@tweet.reach) %>  <%= pluralize(@tweet.reach, 'person', 'people') %></span></span>
              </p>
            </div>
            <div class=" pull-right hover-content" id="<%=@tweet.tweet_id%>">
              <button class='channel_name btn-primary btn send_to_mv'>Send To MV</button>
            </div>
          </div>
          <hr>
          <div class="tweet-navigation">
            <p>Other top <%= @site.tweet_type %> on <%= pretty_date(@date) %>:</p>
            <div class="row">
              <% if @daily_prev %>
              <a href="<%= tweet_path(@daily_prev) %>" class="previous">
                <div class="col-lg-6 col-6">
                  <span class="navigation-number">
                    &lsaquo; <%= @daily_prev.daily_rank %>
                  </span><br>
                  <span class="navigation-name">
                    by @<%= @daily_prev.account.screen_name %>
                  </span>
                </div>
              </a>
              <% else %>
                <div class="col-lg-6 col-6">
                  
                </div>
              <% end %>
              <% if @daily_next %>
              <a href="<%= tweet_path(@daily_next) %>" class="next">
                <div class="col-lg-6 col-6">
                  <span class="navigation-number">
                    <%= @daily_next.daily_rank %> &rsaquo;
                  </span><br>
                  <span class="navigation-name pull-right">
                    by @<%= @daily_next.account.screen_name %>
                  </span>
                </div>
              </a>
              <% else %>
                <div class="col-lg-6 col-6">
                  
                </div>
              <% end %>
            </div>
          </div>

          <hr>
          
          <%= render :partial => "shared/social_sharing_buttons", :locals => { :site => @site } %>
          
        </div>
      </div>
    </div>
  </div>
  <%= render :partial => "sites/login_form_popup" %>
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-12">
          <p>&copy; <%= @date.year %> Measured Voice</p>
          <hr>
          <p><strong><a href="<%= link_to_free_trial(@site) %>">Start your free 30-day 
          trial today</a>.</strong></p>
          <hr>
          <div class="row">
            <div class="col-lg-6 col-12">
              <p><b>What is this?</b></p>
              <p>
                <%=raw @site.explanation %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- JavaScript plugins (requires jQuery) -->
  <script src="http://code.jquery.com/jquery.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="/assets/js/bootstrap.min.js"></script>
  <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

  <!-- Optionally enable responsive features in IE8 -->
  
  <% if @site.google_analytics_code %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '<%= @site.google_analytics_code %>', '<%= @site.host_url %>');
    ga('send', 'pageview');

  </script>
  <% end %>
  </body>
</html>